### PR TITLE
Layer two

### PR DESCRIPTION
**Pull request by JohnnyJumper**

### CODE REVIEW

**Comment by DeRain** [comment]
@JohnnyJumper Test are failing, please take a look

**Comment by JohnnyJumper** [comment]
Failing tests are due to the strange behavior of the command line "swift test" For some reason it doesn't see the need to compile TestHelpers class. This class is used across the tests to avoid duplications of helper code for tests only. 
In XCode setting the TestHelpers class under ResolutionTests target allows me to check the test within the IDE, but looks like we need some other way to tell the swift test command to compile it.

There are some flags that allow talking directly to the compiler and linker, but I am unsure how to use them and if this is the correct approach. Still looking for answers online

**Comment by JohnnyJumper** [comment]
Should be ready to deploy. 
Made sure that the defaults point to mainnet for L2 instead of testnet
Updated changelog and readme files
Updated version in podspec to 3.0.0

**Comment by merenkoff** [comment]
if you need some help to deploy feel free to ask.

**Pull request merged**
